CREATE TABLE Orders (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    OrderNumber NVARCHAR(50) NOT NULL UNIQUE,
    Status NVARCHAR(30) NOT NULL DEFAULT 'PENDING',
    PaymentMethod NVARCHAR(50) NOT NULL,
    ShippingAddress NVARCHAR(500) NOT NULL,
    Subtotal DECIMAL(10,2) NOT NULL DEFAULT 0,
    DiscountTotal DECIMAL(10,2) NOT NULL DEFAULT 0,
    Total DECIMAL(10,2) NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NULL,

    CONSTRAINT FK_Orders_Users FOREIGN KEY (UserId) REFERENCES Users(Id),
    CONSTRAINT CK_Orders_Status CHECK (Status IN ('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT CK_Orders_Amounts CHECK (Subtotal >= 0 AND DiscountTotal >= 0 AND Total >= 0)
);