export const ROUTES = {
  home: '/',
  login: '/auth/login',
  register: '/auth/register',
  forgotPassword: '/auth/forgot-password',
  resetPassword: '/auth/reset-password',
  catalog: '/collections',
  legacyCatalog: '/catalog',
  productDetail: (id: string) => `/collections/${id}`,
  cart: '/cart',
  checkout: '/checkout',
  contact: '/contact',
  privacyPolicy: '/privacy-policy',
  profile: '/profile',
  orderHistory: '/orders',
  orderDetail: (id: string) => `/orders/${id}`,
  wishlist: '/favorites',
  admin: {
    root: '/admin',
    dashboard: '/admin',
    products: '/admin/products',
    promotions: '/admin/promotions',
    reports: '/admin/reports',
  },
} as const;
