CREATE TABLE Cart (
    TID_Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TID_UserId UNIQUEIDENTIFIER NOT NULL,
    TC_Status NVARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    TD_CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    TD_UpdatedAt DATETIME2 NULL,

    CONSTRAINT FK_Carts_Users FOREIGN KEY (TID_UserId) REFERENCES User(TID_Id),
    CONSTRAINT CK_Carts_Status CHECK (TC_Status IN ('ACTIVE', 'CHECKED_OUT', 'ABANDONED'))
);
