CREATE TABLE Carts (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    Status NVARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NULL,

    CONSTRAINT FK_Carts_Users FOREIGN KEY (UserId) REFERENCES Users(Id),
    CONSTRAINT CK_Carts_Status CHECK (Status IN ('ACTIVE', 'CHECKED_OUT', 'ABANDONED'))
);