CREATE TABLE Category (
    TID_Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TC_Name NVARCHAR(100) NOT NULL UNIQUE,
    TC_Description NVARCHAR(255) NULL,
    TB_IsActive BIT NOT NULL DEFAULT 1,
    TD_CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    TD_UpdatedAt DATETIME2 NULL
);
