CREATE TABLE CustomerProfile (
    TID_Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TID_UserId UNIQUEIDENTIFIER NOT NULL UNIQUE,
    TC_IdentificationNumber NVARCHAR(30) NOT NULL UNIQUE,
    TC_FirstName NVARCHAR(100) NOT NULL,
    TC_LastName NVARCHAR(150) NOT NULL,
    TD_BirthDate DATE NULL,
    TC_Phone NVARCHAR(30) NULL,
    TD_CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    TD_UpdatedAt DATETIME2 NULL,

    CONSTRAINT FK_CustomerProfiles_Users FOREIGN KEY (TID_UserId) REFERENCES User(TID_Id)
);
