CREATE TABLE EmailNotifications (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    OrderId UNIQUEIDENTIFIER NULL,
    Type NVARCHAR(50) NOT NULL,
    RecipientEmail NVARCHAR(150) NOT NULL,
    Subject NVARCHAR(255) NOT NULL,
    Status NVARCHAR(30) NOT NULL DEFAULT 'PENDING',
    SentAt DATETIME2 NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT FK_EmailNotifications_Users FOREIGN KEY (UserId) REFERENCES Users(Id),
    CONSTRAINT FK_EmailNotifications_Orders FOREIGN KEY (OrderId) REFERENCES Orders(Id),
    CONSTRAINT CK_EmailNotifications_Type CHECK (Type IN ('ORDER_CONFIRMATION', 'ORDER_STATUS_UPDATE', 'PASSWORD_RESET')),
    CONSTRAINT CK_EmailNotifications_Status CHECK (Status IN ('PENDING', 'SENT', 'FAILED'))
);