CREATE TABLE [Order] (
    TID_Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TID_UserId UNIQUEIDENTIFIER NOT NULL,
    TC_OrderNumber NVARCHAR(50) NOT NULL UNIQUE,
    TC_Status NVARCHAR(30) NOT NULL DEFAULT 'PENDING',
    TC_PaymentMethod NVARCHAR(50) NOT NULL,
    TC_ShippingAddress NVARCHAR(500) NOT NULL,
    TN_Subtotal DECIMAL(10,2) NOT NULL DEFAULT 0,
    TN_DiscountTotal DECIMAL(10,2) NOT NULL DEFAULT 0,
    TN_Total DECIMAL(10,2) NOT NULL DEFAULT 0,
    TD_CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    TD_UpdatedAt DATETIME2 NULL,
    CONSTRAINT FK_Orders_Users FOREIGN KEY (TID_UserId) REFERENCES [User](TID_Id),
    CONSTRAINT CK_Orders_Status CHECK (TC_Status IN ('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    CONSTRAINT CK_Orders_Amounts CHECK (TN_Subtotal >= 0 AND TN_DiscountTotal >= 0 AND TN_Total >= 0)
);