CREATE TABLE PasswordResetToken (
    TID_Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TID_UserId UNIQUEIDENTIFIER NOT NULL,
    TC_TokenHash NVARCHAR(255) NOT NULL,
    TD_ExpiresAt DATETIME2 NOT NULL,
    TD_UsedAt DATETIME2 NULL,
    TD_CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT FK_PasswordResetTokens_Users FOREIGN KEY (TID_UserId) REFERENCES User(TID_Id)
);
