CREATE TABLE ProductImage (
    TID_Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TID_ProductId UNIQUEIDENTIFIER NOT NULL,
    TC_ImageUrl NVARCHAR(500) NOT NULL,
    TC_AltText NVARCHAR(255) NULL,
    TB_IsMain BIT NOT NULL DEFAULT 0,
    TN_SortOrder INT NOT NULL DEFAULT 0,

    CONSTRAINT FK_ProductImages_Products FOREIGN KEY (TID_ProductId) REFERENCES Product(TID_Id)
);
