CREATE TABLE Review (
    TID_Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TID_UserId UNIQUEIDENTIFIER NOT NULL,
    TID_ProductId UNIQUEIDENTIFIER NOT NULL,
    TID_OrderId UNIQUEIDENTIFIER NOT NULL,
    TN_Rating INT NOT NULL,
    TC_Comment NVARCHAR(1000) NULL,
    TD_CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT FK_Reviews_Users FOREIGN KEY (TID_UserId) REFERENCES User(TID_Id),
    CONSTRAINT FK_Reviews_Products FOREIGN KEY (TID_ProductId) REFERENCES Product(TID_Id),
    CONSTRAINT FK_Reviews_Orders FOREIGN KEY (TID_OrderId) REFERENCES Order(TID_Id),
    CONSTRAINT CK_Reviews_Rating CHECK (TN_Rating BETWEEN 1 AND 5),
    CONSTRAINT UQ_Reviews_User_Product UNIQUE (TID_UserId, TID_ProductId)
);
