CREATE TABLE [User] (
    TID_Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TN_RoleId INT NOT NULL,
    TC_Email NVARCHAR(150) NOT NULL UNIQUE,
    TC_PasswordHash NVARCHAR(255) NOT NULL,
    TB_IsActive BIT NOT NULL DEFAULT 1,
    TD_CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    TD_UpdatedAt DATETIME2 NULL,
    CONSTRAINT FK_Users_Roles FOREIGN KEY (TN_RoleId) REFERENCES Role(TID_Id)
);