CREATE TABLE WishlistItem (
    TID_Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TID_UserId UNIQUEIDENTIFIER NOT NULL,
    TID_ProductId UNIQUEIDENTIFIER NOT NULL,
    TD_CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    CONSTRAINT FK_WishlistItems_Users FOREIGN KEY (TID_UserId) REFERENCES [User](TID_Id),
    CONSTRAINT FK_WishlistItems_Products FOREIGN KEY (TID_ProductId) REFERENCES [Product](TID_Id),
    CONSTRAINT UQ_WishlistItems_User_Product UNIQUE (TID_UserId, TID_ProductId)
);