CREATE TABLE WishlistItems (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    ProductId UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),

    CONSTRAINT FK_WishlistItems_Users FOREIGN KEY (UserId) REFERENCES Users(Id),
    CONSTRAINT FK_WishlistItems_Products FOREIGN KEY (ProductId) REFERENCES Products(Id),
    CONSTRAINT UQ_WishlistItems_User_Product UNIQUE (UserId, ProductId)
);